version: "3.7"
services:

 mariadb:
  image: mariadb
  environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=wp

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  depends_on:
    - mariadb
  ports:
   - 8080:80
  environment:
   - PMA_HOST=mariadb

 mailhog:
  image: mailhog/mailhog
  ports:
   - 1025:1025 #smtp server
   - 8025:8025 # web ui